name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Cache bust CSS and JS
      run: |
        # Add timestamp to CSS and JS files to bust cache
        timestamp=$(date +%s)
        sed -i "s/main.css?v=[0-9]*/main.css?v=$timestamp/g" index.html
        sed -i "s/script.js?v=[0-9]*/script.js?v=$timestamp/g" index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        cname: 
        commit_message: "Deploy with cache busting - ${{ github.sha }}" 